name: Build and Test
on: [push]
jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
        - name: Install Rosie
          run: |
            git clone https://gitlab.com/rosie-pattern-language/rosie.git
            cd rosie
            make
            make install
        - name: Build Rosie Go
          run: go run rtest.go
